package client

type GetUsersRequest struct {}
type GetUsersResponse struct {}
type GetUserRequest struct {}
type GetUserResponse struct {}
type GetUserAppsRequest struct {}
type GetUserAppsResponse struct {}
type GetUserRolesRequest struct {}
type GetUserRolesResponse struct {}
type GetCustomAttributesRequest struct {}
type GetCustomAttributesResponse struct {}
type CreateUserRequest struct {}
type CreateUserResponse struct {}
type UpdateUserRequest struct {}
type UpdateUserResponse struct {}
type AssignRoleToUserRequest struct {}
type AssignRoleToUserResponse struct {}
type RemoveRoleFromUserRequest struct {}
type RemoveRoleFromUserResponse struct {}
type SetPasswordUsingClearTextRequest struct {}
type SetPasswordUsingClearTextResponse struct {}
type SetPasswordUsingHashSaltRequest struct {}
type SetPasswordUsingHashSaltResponse struct {}
type SetStateToUserRequest struct {}
type SetStateToUserResponse struct {}
type SetCustomAttributeToUserRequest struct {}
type SetCustomAttributeToUserResponse struct {}
type LogUserOutRequest struct {}
type LogUserOutResponse struct {}
type LockUserRequest struct {}
type LockUserResponse struct {}
type DeleteUserRequest struct {}
type DeleteUserResponse struct {}
type GenerateUserMFATokenRequest struct {}
type GenerateUserMFATokenResponse struct {}
